################################################################################
# The source code contained or described herein and all documents related to
# the source code ("Material") are owned by Intel Corporation. Title to the
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
################################################################################

version: '3.6'

services:

  #----Start: EIS Base Images -- This Base images must be included for building any EIS servcies ----
  # Define ia_eisbase service
  ia_eisbase:
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.eisbase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          EIS_VERSION: ${EIS_VERSION}
          HOST_TIME_ZONE: ${HOST_TIME_ZONE}
          ETCD_HOST: ${ETCD_HOST}
    read_only: true
    image: ${DOCKER_REGISTRY}ia_eisbase:${EIS_VERSION}

  ## Define ia_common service
  ia_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.common
      args:
          EIS_VERSION: ${EIS_VERSION}
          # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
          CMAKE_BUILD_TYPE: "Release"
          ETCD_HOST: ${ETCD_HOST}
    read_only: true
    image: ${DOCKER_REGISTRY}ia_common:${EIS_VERSION}

  #----End: EIS Base Images---- -- This Base images must be included for building any EIS servcies ----

 # UWC containers
 # 1. uwc_common
 # 2. modbus-tcp-master
 # 3. modbus-rtu-master
 # 4. mqtt_container
 # 5. mqtt-export
 # 6. scada-rtu

  ## uwc_common image
  uwc_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../uwc_common
      dockerfile: $PWD/../uwc_common/Dockerfile.common
      args:
          EIS_VERSION: ${EIS_VERSION}
    read_only: true
    image: ${DOCKER_REGISTRY}uwc_common:${EIS_VERSION}

  modbus-tcp-master:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        ETCD_HOST: ${ETCD_HOST}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: ${DOCKER_REGISTRY}modbus-master:${EIS_VERSION}
    container_name: modbus-tcp-master
    hostname: modbus-tcp-master
    read_only: true
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "TCP"
      ETCD_HOST: ${ETCD_HOST}
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000"
      MY_APP_ID: 1
      CUTOFF_INTERVAL_PERCENTAGE: 90
      CertType: "zmq"
      BUILD_NUMBER: ${BUILD_NUMBER}
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT_Export,KPIAPP"
      NETWORK_TYPE: TCP
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      PubTopics: "TCP_PolledData,TCP_PolledData_RT,TCP_RdResp,TCP_RdResp_RT,TCP_WrResp,TCP_WrResp_RT"
      SubTopics: "MQTT_Export/MQTT_Export_RdReq,MQTT_Export/MQTT_Export_RdReq_RT,MQTT_Export/MQTT_Export_WrReq,MQTT_Export/MQTT_Export_WrReq_RT,KPIAPP/KPIAPP_WrReq,KPIAPP/KPIAPP_WrReq_RT"
      # non-realtime topics
      TCP_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      # realtime topics
      TCP_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      KPIAPP_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      KPIAPP_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    volumes:
      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
      - "vol_uwc_socket:${SOCKET_DIR}:z"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "${EIS_INSTALL_PATH}/container_logs/modbus-tcp-master:/opt/intel/app/logs"
    user: ${EIS_UID}
    # userns_mode: host
    secrets:
      - ca_etcd
      - etcd_TCP_cert
      - etcd_TCP_key
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh","-c", "ps -C ModbusMaster >/dev/null && echo Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

  modbus-rtu-master:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile_RTU
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        ETCD_HOST: ${ETCD_HOST}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: ${DOCKER_REGISTRY}modbus-rtu-master:${EIS_VERSION}
    container_name: modbus-rtu-master
    hostname: modbus-rtu-master
    read_only: true
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "RTU"
      ETCD_HOST: ${ETCD_HOST}
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000"
      CUTOFF_INTERVAL_PERCENTAGE: 90
      SERIAL_PORT_RETRY_INTERVAL: 1
      MY_APP_ID: 2
      CertType: "zmq"
      BUILD_NUMBER: ${BUILD_NUMBER}
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT_Export,KPIAPP"
      NETWORK_TYPE: RTU
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      PubTopics: "RTU_PolledData,RTU_RdResp,RTU_WrResp,RTU_PolledData_RT,RTU_RdResp_RT,RTU_WrResp_RT"
      SubTopics: "MQTT_Export/MQTT_Export_RdReq,MQTT_Export/MQTT_Export_WrReq,MQTT_Export/MQTT_Export_RdReq_RT,MQTT_Export/MQTT_Export_WrReq_RT,KPIAPP/KPIAPP_WrReq,KPIAPP/KPIAPP_WrReq_RT"
      # non-realtime topics
      RTU_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      # realtime topics
      RTU_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      KPIAPP_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      KPIAPP_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    volumes:
      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "vol_uwc_socket:${SOCKET_DIR}:z"
      - "${EIS_INSTALL_PATH}/container_logs/modbus-rtu-master:/opt/intel/app/logs"
    user: ${EIS_UID}
   #userns_mode: host
    devices:
      - /dev:/dev
    privileged: true
    secrets:
      - ca_etcd
      - etcd_RTU_cert
      - etcd_RTU_key
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh","-c", "ps -C ModbusMaster >/dev/null && echo Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

  mqtt_container:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../MQTT/
      dockerfile: $PWD/../MQTT/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: ${DOCKER_REGISTRY}mqtt_container:${EIS_VERSION}
    container_name: mqtt_container
    hostname: mqtt_container
    read_only: true
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    environment:
      AppName: "MQTT"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      BUILD_NUMBER: ${BUILD_NUMBER}
    user: ${EIS_UID}
    # userns_mode: host
    secrets:
      - ca_broker
      - broker_cert
      - broker_key
    security_opt:
      - no-new-privileges
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ["CMD-SHELL", "timeout --foreground 5 mosquitto_sub --cafile /run/secrets/ca_broker -h 127.0.0.1 -p 11883 --cert /run/secrets/broker_cert --key /run/secrets/broker_key -t '$$SYS/#' -C 1 | grep -v Error || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

  mqtt-export:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../mqtt-export/
      dockerfile: $PWD/../mqtt-export/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        ETCD_HOST: ${ETCD_HOST}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: ${DOCKER_REGISTRY}mqtt-export:${EIS_VERSION}
    container_name: mqtt-export
    hostname: mqtt-export
    read_only: true
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "MQTT_Export"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      ETCD_HOST: ${ETCD_HOST}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000" 
      MQTT_URL_FOR_EXPORT: "ssl://mqtt_container:11883"
      CertType: "zmq"
      BUILD_NUMBER: ${BUILD_NUMBER}
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "TCP,RTU"
      SubTopics: "TCP/TCP_PolledData,TCP/TCP_RdResp,TCP/TCP_WrResp,RTU/RTU_PolledData,RTU/RTU_RdResp,RTU/RTU_WrResp,TCP/TCP_PolledData_RT,TCP/TCP_RdResp_RT,TCP/TCP_WrResp_RT,RTU/RTU_PolledData_RT,RTU/RTU_RdResp_RT,RTU/RTU_WrResp_RT"
      PubTopics: "MQTT_Export_RdReq,MQTT_Export_WrReq,MQTT_Export_RdReq_RT,MQTT_Export_WrReq_RT"
      # non-realtime topics
      TCP_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      ReadRequest: MQTT_Export_RdReq
      WriteRequest: MQTT_Export_WrReq
      # realtime topics
      TCP_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      ReadRequest_RT: MQTT_Export_RdReq_RT
      WriteRequest_RT: MQTT_Export_WrReq_RT
      # general topics
      mqtt_SubReadTopic: "/+/+/+/read"
      mqtt_SubWriteTopic: "/+/+/+/write"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    user: ${EIS_UID}
    # userns_mode: host
    volumes:
      - "vol_uwc_socket:${SOCKET_DIR}:z"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "${EIS_INSTALL_PATH}/container_logs/mqtt-export:/opt/intel/app/logs"
    secrets:
      - ca_etcd
      - etcd_MQTT_Export_cert
      - etcd_MQTT_Export_key
      - ca_broker
      - client_cert
      - client_key
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh","-c", "ps -C MQTT_Export >/dev/null && echo Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

  scada-rtu:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../scada-rtu/
      dockerfile: $PWD/../scada-rtu/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        ETCD_HOST: ${ETCD_HOST}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: ${DOCKER_REGISTRY}scada-rtu:${EIS_VERSION}
    container_name: scada-rtu
    hostname: scada-rtu
    read_only: true
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "SCADA-RTU"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      INTERNAL_MQTT_URL: "ssl://mqtt_container:11883"
      NETWORK_TYPE: "ALL"
      TOPIC_SEPARATOR: '-'
      CertType: "zmq"
      BUILD_NUMBER: ${BUILD_NUMBER}
      PROFILING_MODE: ${PROFILING_MODE}
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    user: ${EIS_UID}
    volumes:
     - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
     - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
     - "${EIS_INSTALL_PATH}/container_logs/scada-rtu:/opt/intel/app/logs"
    secrets:
      - ca_etcd
      - etcd_SCADA-RTU_cert
      - etcd_SCADA-RTU_key
      - ca_broker
      - client_cert
      - client_key
      - scadahost_ca_cert
      - scadahost_client_key
      - scadahost_client_cert      
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh","-c", "ps -C SCADARTU >/dev/null && echo Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

  kpi-tactic:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../kpi-tactic/
      dockerfile: $PWD/../kpi-tactic/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
        ETCD_HOST: ${ETCD_HOST}
        BUILD_NUMBER: ${BUILD_NUMBER}
    image: ${DOCKER_REGISTRY}kpi-tactic:${EIS_VERSION}
    container_name: kpi-tactic-app
    hostname: kpi-tactic
    read_only: true
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "KPIAPP"
      ETCD_HOST: ${ETCD_HOST}
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      MQTT_URL: "ssl://mqtt_container:11883"
      KPIAPPConfigFile: "ControlLoopConfig.yml"
      Clients: "TCP,RTU"
      CertType: "zmq"
      BUILD_NUMBER: ${BUILD_NUMBER}
      PROFILING_MODE: ${PROFILING_MODE}
      SubTopics: "TCP/TCP_PolledData,TCP/TCP_WrResp,RTU/RTU_PolledData,RTU/RTU_WrResp,TCP/TCP_PolledData_RT,TCP/TCP_WrResp_RT,RTU/RTU_PolledData_RT,RTU/RTU_WrResp_RT"
      PubTopics: "KPIAPP_WrReq,KPIAPP_WrReq_RT"
      WriteRequest_RT: "KPIAPP_WrReq_RT"
      WriteRequest: "KPIAPP_WrReq"
      TCP_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      KPIAPP_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      KPIAPP_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    user: ${EIS_UID}
    volumes:
     - "vol_uwc_socket:${SOCKET_DIR}:z"
     - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
     - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
     - "${EIS_INSTALL_PATH}/container_logs/kpi-tactic:/opt/intel/app/logs"
    secrets:
      - ca_etcd
      - etcd_KPIAPP_cert
      - etcd_KPIAPP_key
      - ca_broker
      - client_cert
      - client_key     
    security_opt:
      - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh","-c", "ps -C KPIAPP >/dev/null && echo Running || echo Not running; exit 1"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 0s

volumes:
  vol_uwc_socket:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${EIS_INSTALL_PATH}/sockets
  vol_etcd_keeper:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

networks:
  default:
    external:
      name: uwc_nw

secrets:
  ca_etcd:
    file: provision/Certificates/ca/ca_certificate.pem
  etcd_root_cert:
    file: provision/Certificates/root/root_client_certificate.pem
  etcd_root_key:
    file: provision/Certificates/root/root_client_key.pem
  etcd_TCP_cert:
    file: provision/Certificates/TCP/TCP_client_certificate.pem
  etcd_TCP_key:
    file: provision/Certificates/TCP/TCP_client_key.pem
  etcd_RTU_cert:
    file: provision/Certificates/RTU/RTU_client_certificate.pem
  etcd_RTU_key:
    file: provision/Certificates/RTU/RTU_client_key.pem
  etcd_MQTT_Export_cert:
    file: provision/Certificates/MQTT_Export/MQTT_Export_client_certificate.pem
  etcd_MQTT_Export_key:
    file: provision/Certificates/MQTT_Export/MQTT_Export_client_key.pem
  etcd_SCADA-RTU_cert:
    file: provision/Certificates/SCADA-RTU/SCADA-RTU_client_certificate.pem
  etcd_SCADA-RTU_key:
    file: provision/Certificates/SCADA-RTU/SCADA-RTU_client_key.pem
  etcd_KPIAPP_cert:
    file: provision/Certificates/KPIAPP/KPIAPP_client_certificate.pem
  etcd_KPIAPP_key:
    file: provision/Certificates/KPIAPP/KPIAPP_client_key.pem
  ca_broker:
    file: provision/Certificates/ca/ca_certificate.pem
  broker_cert:
    file: provision/Certificates/mymqttcerts/mymqttcerts_server_certificate.pem
  broker_key:
    file: provision/Certificates/mymqttcerts/mymqttcerts_server_key.pem
  client_cert:
    file: provision/Certificates/mymqttcerts/mymqttcerts_client_certificate.pem
  client_key:
    file: provision/Certificates/mymqttcerts/mymqttcerts_client_key.pem
  scadahost_ca_cert:
    file: provision/Certificates/scada_ext_certs/ca/root-ca.crt
  scadahost_client_cert:
    file: provision/Certificates/scada_ext_certs/client_crt/client.crt
  scadahost_client_key:
    file: provision/Certificates/scada_ext_certs/client_key/client.key

