################################################################################
# The source code contained or described herein and all documents related to
# the source code ("Material") are owned by Intel Corporation. Title to the
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
################################################################################

version: '3.6'

services:

  #----Start: EIS Base Images -- This Base images must be included for building any EIS servcies ----
  # Define ia_eisbase service
  ia_eisbase:
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.eisbase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          EIS_VERSION: ${EIS_VERSION}
    image: ${DOCKER_REGISTRY}ia_eisbase:${EIS_VERSION}

  ## Define ia_common service
  ia_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.common
      args:
          EIS_VERSION: ${EIS_VERSION}
          # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
          CMAKE_BUILD_TYPE: "Release"
    read_only: true
    image: ${DOCKER_REGISTRY}ia_common:${EIS_VERSION}

  #----End: EIS Base Images---- -- This Base images must be included for building any EIS servcies ----

 # UWC containers
 # 1. uwc_common
 # 2. modbus-tcp-master
 # 3. modbus-rtu-master
 # 4. mqtt_container
 # 5. mqtt-export
 # 6. scada-rtu

  ## uwc_common image
  uwc_test_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../uwc_common
      dockerfile: $PWD/../uwc_common/Dockerfile.common.test
      args:
          EIS_VERSION: ${EIS_VERSION}
    read_only: true
    image: ${DOCKER_REGISTRY}uwc_test_common:${EIS_VERSION}

  modbus-tcp-master-test:
    depends_on:
      - ia_eisbase
      - uwc_test_common
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile_UT
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-master-test:${EIS_VERSION}
    container_name: modbus-tcp-master-test
    hostname: modbus-tcp-master-test
    network_mode: host
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "TCP"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/Modbus-App/Config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000"
      MY_APP_ID: 1
      NETWORK_TYPE: TCP
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT_Export"
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      PubTopics: "TCP_PolledData,TCP_PolledData_RT,TCP_RdResp,TCP_RdResp_RT,TCP_WrResp,TCP_WrResp_RT"
      SubTopics: "MQTT_Export/MQTT_Export_RdReq,MQTT_Export/MQTT_Export_RdReq_RT,MQTT_Export/MQTT_Export_WrReq,MQTT_Export/MQTT_Export_WrReq_RT"
      # non-realtime topics
      TCP_PolledData_cfg: "zmq_tcp,127.0.0.1:6000"
      TCP_RdResp_cfg: "zmq_tcp,127.0.0.1:6001"
      TCP_WrResp_cfg: "zmq_tcp,127.0.0.1:6002"
      MQTT_Export_RdReq_cfg: "zmq_tcp,127.0.0.1:6003"
      MQTT_Export_WrReq_cfg: "zmq_tcp,127.0.0.1:6004"
      # realtime topics
      TCP_PolledData_RT_cfg: "zmq_tcp,127.0.0.1:6005"
      TCP_RdResp_RT_cfg: "zmq_tcp,127.0.0.1:6006"
      TCP_WrResp_RT_cfg: "zmq_tcp,127.0.0.1:6007"
      MQTT_Export_RdReq_RT_cfg: "zmq_tcp,127.0.0.1:6008"
      MQTT_Export_WrReq_RT_cfg: "zmq_tcp,127.0.0.1:6009"
    volumes:
      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "$PWD/unit_test_reports/modbus-tcp-master:/reports/modbus-tcp-master"

  modbus-rtu-test-master:
    depends_on:
      - ia_eisbase
      - uwc_test_common
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile_UT_RTU
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-rtu-test-master:${EIS_VERSION}
    container_name: modbus-rtu-test-master
    hostname: modbus-rtu-test-master
    network_mode: host
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "RTU"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/Modbus-App/Config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000"
      SERIAL_PORT_RETRY_INTERVAL: 1
      MY_APP_ID: 2
      NETWORK_TYPE: RTU
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT_Export"
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      PubTopics: "RTU_PolledData,RTU_RdResp,RTU_WrResp,RTU_PolledData_RT,RTU_RdResp_RT,RTU_WrResp_RT"
      SubTopics: "MQTT_Export/MQTT_Export_RdReq,MQTT_Export/MQTT_Export_WrReq,MQTT_Export/MQTT_Export_RdReq_RT,MQTT_Export/MQTT_Export_WrReq_RT"
      # non-realtime topics
      RTU_PolledData_cfg: "zmq_tcp,127.0.0.1:6010"
      RTU_RdResp_cfg: "zmq_tcp,127.0.0.1:6011"
      RTU_WrResp_cfg: "zmq_tcp,127.0.0.1:6012"
      MQTT_Export_RdReq_cfg: "zmq_tcp,127.0.0.1:6003"
      MQTT_Export_WrReq_cfg: "zmq_tcp,127.0.0.1:6004"
      # realtime topics
      RTU_PolledData_RT_cfg: "zmq_tcp,127.0.0.1:6013"
      RTU_RdResp_RT_cfg: "zmq_tcp,127.0.0.1:6014"
      RTU_WrResp_RT_cfg: "zmq_tcp,127.0.0.1:6015"
      MQTT_Export_RdReq_RT_cfg: "zmq_tcp,127.0.0.1:6008"
      MQTT_Export_WrReq_RT_cfg: "zmq_tcp,127.0.0.1:6009"
    volumes:
      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "$PWD/unit_test_reports/modbus-rtu-master:/reports/modbus-rtu-master"
    devices:
      - /dev:/dev
    privileged: true

  mqtt_test_container:
    depends_on:
      - ia_eisbase
      - uwc_test_common
    build:
      context: $PWD/../MQTT/
      dockerfile: $PWD/../MQTT/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
    image: ${DOCKER_REGISTRY}mqtt_test_container:${EIS_VERSION}
    container_name: mqtt_test_container
    hostname: mqtt_test_container
    network_mode: host
    environment:
      AppName: "MQTT"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}

  mqtt-export-test:
    depends_on:
      - ia_eisbase
      - uwc_test_common
    build:
      context: $PWD/../mqtt-export/
      dockerfile: $PWD/../mqtt-export/Dockerfile_UT
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}mqtt-export-test:${EIS_VERSION}
    container_name: mqtt-export-test
    hostname: mqtt-export-test
    network_mode: host
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "MQTT_Export_TEST"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/MQTT-Export-App/Config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000" 
      MQTT_URL_FOR_EXPORT: "tcp://127.0.0.1:11883"
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "TCP,RTU"
      SubTopics: "TCP/TCP_PolledData,TCP/TCP_RdResp,TCP/TCP_WrResp,RTU/RTU_PolledData,RTU/RTU_RdResp,RTU/RTU_WrResp,TCP/TCP_PolledData_RT,TCP/TCP_RdResp_RT,TCP/TCP_WrResp_RT,RTU/RTU_PolledData_RT,RTU/RTU_RdResp_RT,RTU/RTU_WrResp_RT"
      PubTopics: "MQTT_Export_RdReq,MQTT_Export_WrReq,MQTT_Export_RdReq_RT,MQTT_Export_WrReq_RT"
      # non-realtime topics
      TCP_PolledData_cfg: "zmq_tcp,127.0.0.1:6000"
      TCP_RdResp_cfg: "zmq_tcp,127.0.0.1:6001"
      TCP_WrResp_cfg: "zmq_tcp,127.0.0.1:6002"
      RTU_PolledData_cfg: "zmq_tcp,127.0.0.1:6010"
      RTU_RdResp_cfg: "zmq_tcp,127.0.0.1:6011"
      RTU_WrResp_cfg: "zmq_tcp,127.0.0.1:6012"
      ReadRequest: "MQTT_Export_RdReq"
      WriteRequest: "MQTT_Export_WrReq"
      MQTT_Export_RdReq_cfg: "zmq_tcp,127.0.0.1:6003"
      MQTT_Export_WrReq_cfg: "zmq_tcp,127.0.0.1:6004"
      # realtime topics
      TCP_PolledData_RT_cfg: "zmq_tcp,127.0.0.1:6005"
      TCP_RdResp_RT_cfg: "zmq_tcp,127.0.0.1:6006"
      TCP_WrResp_RT_cfg: "zmq_tcp,127.0.0.1:6007"
      RTU_PolledData_RT_cfg: "zmq_tcp,127.0.0.1:6013"
      RTU_RdResp_RT_cfg: "zmq_tcp,127.0.0.1:6014"
      RTU_WrResp_RT_cfg: "zmq_tcp,127.0.0.1:6015"
      ReadRequest_RT: "MQTT_Export_RdReq_RT"
      WriteRequest_RT: "MQTT_Export_WrReq_RT"
      MQTT_Export_RdReq_RT_cfg: "zmq_tcp,127.0.0.1:6008"
      MQTT_Export_WrReq_RT_cfg: "zmq_tcp,127.0.0.1:6009"
      # general topics
      mqtt_SubReadTopic: "/+/+/+/read"
      mqtt_SubWriteTopic: "/+/+/+/write"
    volumes:
      - "$PWD/unit_test_reports/mqtt-export:/reports/mqtt-export"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"

#  scada-rtu-test:
#    depends_on:
#      - ia_eisbase
#      - uwc_test_common
#    build:
#      context: $PWD/../scada-rtu/
#      dockerfile: $PWD/../scada-rtu/Dockerfile_UT
#      args:
#        EIS_VERSION: ${EIS_VERSION}
#        EIS_UID: ${EIS_UID}
#        EIS_USER_NAME: ${EIS_USER_NAME}
#    image: ${DOCKER_REGISTRY}scada-rtu:${EIS_VERSION}
#    container_name: scada-rtu-test
#    hostname: scada-rtu-test
#    network_mode: host
#    ulimits:
#     rtprio:
#       soft: "99" # these are the maximum values of priorites to be used inside the container application
#       hard: "99"
#    environment:
#      AppName: "SCADA-RTU-TEST"
#      DEV_MODE: ${DEV_MODE}
#      no_proxy: ${no_proxy}
#      Log4cppPropsFile: "/SCADA-RTU-APP/Config/log4cpp.properties"
#      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
#      NETWORK_TYPE: "ALL"
#      MQTT_URL: ""
#      CertType: "zmq"
#      PROFILING_MODE: ${PROFILING_MODE}
#    logging:
#        driver: "json-file"
#        options:
#            max-file: "3"
#            max-size: "10m"
#    volumes:
#      - "$PWD/unit_test_reports/scada-rtu:/reports/scada-rtu"
#      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
#      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
#      - "${EIS_INSTALL_PATH}/container_logs/scada-rtu:/opt/intel/app/logs"
