################################################################################
# The source code contained or described herein and all documents related to
# the source code ("Material") are owned by Intel Corporation. Title to the
# Material remains with Intel Corporation.
#
# No license under any patent, copyright, trade secret or other intellectual
# property right is granted to or conferred upon you by disclosure or delivery of
# the Materials, either expressly, by implication, inducement, estoppel or otherwise.
################################################################################

version: '3.6'

services:

  #----Start: EIS Base Images -- This Base images must be included for building any EIS servcies ----
  # Define ia_eisbase service
  ia_eisbase:
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.eisbase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          EIS_VERSION: ${EIS_VERSION}
          HOST_TIME_ZONE: ${HOST_TIME_ZONE}
    image: ${DOCKER_REGISTRY}ia_eisbase:${EIS_VERSION}

  ## Define ia_common service
  ia_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.common
      args:
          EIS_VERSION: ${EIS_VERSION}
          # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
          CMAKE_BUILD_TYPE: "Release"
    read_only: true
    image: ${DOCKER_REGISTRY}ia_common:${EIS_VERSION}

  #----End: EIS Base Images---- -- This Base images must be included for building any EIS servcies ----

  ## Define ETCD UI service - must be included to view ETCD data over web UI
  ia_etcd_ui:
    depends_on:
      - ia_common
    build:
      context: $PWD/../EtcdUI
      dockerfile: $PWD/../EtcdUI/Dockerfile
      args:
        ETCD_KEEPER_VERSION: ${ETCD_KEEPER_VERSION}
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
    read_only: true
    image: ${DOCKER_REGISTRY}ia_etcd_ui:${EIS_VERSION}
    container_name: ia_etcd_ui
    hostname: ia_etcd_ui
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "EtcdUi"
      DEV_MODE: ${DEV_MODE}
      NGINX_PORT: 7071
      CertType: "pem"
      no_proxy: ${eis_no_proxy},${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
    volumes:
      - "vol_etcd_keeper:/tmp/nginx"
    user: ${EIS_UID}

 # UWC containers
 # 1. uwc_common
 # 2. modbus-tcp-master
 # 3. modbus-rtu-master
 # 4. mqtt_container
 # 5. mqtt-export
 # 6. scada-rtu

  ## uwc_common image
  uwc_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../uwc_common
      dockerfile: $PWD/../uwc_common/Dockerfile.common
      args:
          EIS_VERSION: ${EIS_VERSION}
    read_only: true
    image: ${DOCKER_REGISTRY}uwc_common:${EIS_VERSION}

  modbus-tcp-master:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-master:${EIS_VERSION}
    container_name: modbus-tcp-master
    hostname: modbus-tcp-master
    network_mode: host
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "TCP"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000"
      MY_APP_ID: 1
      CUTOFF_INTERVAL_PERCENTAGE: 90
      CertType: "zmq"
      NETWORK_TYPE: TCP
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT_Export"
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      PubTopics: "TCP_PolledData,TCP_PolledData_RT,TCP_RdResp,TCP_RdResp_RT,TCP_WrResp,TCP_WrResp_RT"
      SubTopics: "MQTT_Export/MQTT_Export_RdReq,MQTT_Export/MQTT_Export_RdReq_RT,MQTT_Export/MQTT_Export_WrReq,MQTT_Export/MQTT_Export_WrReq_RT"
      # non-realtime topics
      TCP_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      # realtime topics
      TCP_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    volumes:
      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "vol_uwc_socket:${SOCKET_DIR}"
    user: ${EIS_UID}

  modbus-rtu-master:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile_RTU
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-rtu-master:${EIS_VERSION}
    container_name: modbus-rtu-master
    hostname: modbus-rtu-master
    network_mode: host
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "RTU"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000"
      CUTOFF_INTERVAL_PERCENTAGE: 90
      SERIAL_PORT_RETRY_INTERVAL: 1
      BAUD_RATE: 9600
      PARITY: "E"
      PORT_NAME: "/dev/ttyUSB0"
      MY_APP_ID: 2
      NETWORK_TYPE: RTU
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT_Export"
      DEVICES_GROUP_LIST_FILE_NAME: "Devices_group_list.yml"
      PubTopics: "RTU_PolledData,RTU_RdResp,RTU_WrResp,RTU_PolledData_RT,RTU_RdResp_RT,RTU_WrResp_RT"
      SubTopics: "MQTT_Export/MQTT_Export_RdReq,MQTT_Export/MQTT_Export_WrReq,MQTT_Export/MQTT_Export_RdReq_RT,MQTT_Export/MQTT_Export_WrReq_RT"
      # non-realtime topics
      RTU_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      # realtime topics
      RTU_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    volumes:
      - "${EIS_INSTALL_PATH}/uwc_data:/opt/intel/eis/uwc_data:ro"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"
      - "vol_uwc_socket:${SOCKET_DIR}"
    user: ${EIS_UID}
    devices:
      - /dev:/dev
    privileged: true

  mqtt_container:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../MQTT/
      dockerfile: $PWD/../MQTT/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
    image: ${DOCKER_REGISTRY}mqtt_container:${EIS_VERSION}
    container_name: mqtt_container
    hostname: mqtt_container
    network_mode: host
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    environment:
      AppName: "MQTT"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
    user: ${EIS_UID}

  mqtt-export:
    depends_on:
      - ia_eisbase
      - uwc_common
    build:
      context: $PWD/../mqtt-export/
      dockerfile: $PWD/../mqtt-export/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}mqtt-export:${EIS_VERSION}
    container_name: mqtt-export
    hostname: mqtt-export
    network_mode: host
    restart: unless-stopped
    ulimits:
     rtprio:
       soft: "99" # these are the maximum values of priorites to be used inside the container application
       hard: "99"
    environment:
      AppName: "MQTT_Export"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
      ZMQ_RECV_HWM: "1000" 
      MQTT_URL_FOR_EXPORT: "tcp://127.0.0.1:11883"
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "TCP,RTU"
      SubTopics: "TCP/TCP_PolledData,TCP/TCP_RdResp,TCP/TCP_WrResp,RTU/RTU_PolledData,RTU/RTU_RdResp,RTU/RTU_WrResp,TCP/TCP_PolledData_RT,TCP/TCP_RdResp_RT,TCP/TCP_WrResp_RT,RTU/RTU_PolledData_RT,RTU/RTU_RdResp_RT,RTU/RTU_WrResp_RT"
      PubTopics: "MQTT_Export_RdReq,MQTT_Export_WrReq,MQTT_Export_RdReq_RT,MQTT_Export_WrReq_RT"
      # non-realtime topics
      TCP_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_PolledData_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_cfg: "zmq_ipc,${SOCKET_DIR}/"
      ReadRequest: MQTT_Export_RdReq
      WriteRequest: MQTT_Export_WrReq
      # realtime topics
      TCP_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_RdReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      MQTT_Export_WrReq_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      TCP_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_PolledData_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_RdResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      RTU_WrResp_RT_cfg: "zmq_ipc,${SOCKET_DIR}/"
      ReadRequest_RT: MQTT_Export_RdReq_RT
      WriteRequest_RT: MQTT_Export_WrReq_RT
      # general topics
      mqtt_SubReadTopic: "/+/+/+/read"
      mqtt_SubWriteTopic: "/+/+/+/write"
    logging:
        driver: "json-file"
        options:
            max-file: "3"
            max-size: "10m"
    user: ${EIS_UID}
    volumes:
      - "vol_uwc_socket:${SOCKET_DIR}"
      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"

#  scada-rtu:
#    depends_on:
#      - ia_eisbase
#      - uwc_common
#    build:
#      context: $PWD/../scada-rtu/
#      dockerfile: $PWD/../scada-rtu/Dockerfile
#      args:
#        EIS_VERSION: ${EIS_VERSION}
#        EIS_UID: ${EIS_UID}
#        EIS_USER_NAME: ${EIS_USER_NAME}
#    image: ${DOCKER_REGISTRY}scada-rtu:${EIS_VERSION}
#    container_name: scada-rtu
#    hostname: scada-rtu
#    network_mode: host
#    restart: unless-stopped
#    ulimits:
#     rtprio:
#       soft: "99" # these are the maximum values of priorites to be used inside the container application
#       hard: "99"
#    environment:
#      AppName: "SCADA-RTU"
#      DEV_MODE: ${DEV_MODE}
#      no_proxy: ${no_proxy}
#      Log4cppPropsFile: "/opt/intel/config/log4cpp.properties"
#      MQTT_URL: "tcp://127.0.0.1:11883"
#      CertType: "zmq"
#      PROFILING_MODE: ${PROFILING_MODE}
#    logging:
#        driver: "json-file"
#        options:
#            max-file: "3"
#            max-size: "10m"
#    user: ${EIS_UID}
#    volumes:
#      - "vol_uwc_socket:${SOCKET_DIR}"
#      - "${EIS_INSTALL_PATH}/uwc_data/common_config:${EIS_INSTALL_PATH}/uwc_data/common_config:ro"

volumes:
  vol_uwc_socket:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${EIS_INSTALL_PATH}/sockets
  vol_etcd_keeper:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
