version: '3.6'

services:

  #----Start: EIS Base Images -- This Base images must be included for building any EIS servcies ----
  # Define ia_eisbase service
  ia_common:
    build:
      context:  $PWD/../common
      dockerfile:  $PWD/../common/dockerfiles/Dockerfile.common
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          EIS_VERSION: ${EIS_VERSION}
    image: ${DOCKER_REGISTRY}ia_common:${EIS_VERSION}
  
  ia_eisbase:
    depends_on:
      - ia_common
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.eisbase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          EIS_VERSION: ${EIS_VERSION}
    image: ${DOCKER_REGISTRY}ia_eisbase:${EIS_VERSION}

  #----End: EIS Base Images---- -- This Base images must be included for building any EIS servcies ----

  # Define ETCD UI service - must be included to view ETCD data over web UI
  ia_etcd_ui:
    build:
      context: $PWD/../EtcdUI
      dockerfile: $PWD/../EtcdUI/Dockerfile
      args:
        ETCD_KEEPER_VERSION: ${ETCD_KEEPER_VERSION}
        EIS_VERSION: ${EIS_VERSION}
    image: ${DOCKER_REGISTRY}ia_etcd_ui:${EIS_VERSION}
    container_name: ia_etcd_ui
    hostname: ia_etcd_ui
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "EtcdUi"
      DEV_MODE: ${DEV_MODE}
    user: ${EIS_UID}
 
  modbus-tcp-master:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-master:${EIS_VERSION}
    container_name: modbus-tcp-master
    hostname: modbus-tcp-master
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "CppPub"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      TCP_ENABLED : 1
      MODBUS_MASTER_CONNECT_TIMEOUT: 30000
      MODBUS_MASTER_SESSION_TIMEOUT: 10
      CONFIG_FILE_PATH: /opt/config/
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "DemoApp,Subscriber"
      PubTopics: "PL0_flowmeter1,PL1_flowmeter2"
      PL0_flowmeter1_cfg: "zmq_tcp,127.0.0.1:5656"
      PL1_flowmeter2_cfg: "zmq_tcp,127.0.0.1:5757"
    volumes:
      - "./config/UWC_Config:/opt/config"
    #user: ${EIS_UID}
