version: '3.6'

services:

  #----Start: EIS Base Images -- This Base images must be included for building any EIS servcies ----
  # Define ia_eisbase service
  ia_eisbase:
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.eisbase
      args:
          UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
          EIS_VERSION: ${EIS_VERSION}
    image: ${DOCKER_REGISTRY}ia_eisbase:${EIS_VERSION}

  ## Define ia_common service
  ia_common:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../common
      dockerfile: $PWD/../common/dockerfiles/Dockerfile.common
      args:
          EIS_VERSION: ${EIS_VERSION}
          # set CMAKE_BUILD_TYPE value to "Debug" to generate debug symbols
          CMAKE_BUILD_TYPE: "Release"
    read_only: true
    image: ${DOCKER_REGISTRY}ia_common:${EIS_VERSION}

  #----End: EIS Base Images---- -- This Base images must be included for building any EIS servcies ----

  # Define ETCD UI service - must be included to view ETCD data over web UI
  ia_etcd_ui:
    build:
      context: $PWD/../EtcdUI
      dockerfile: $PWD/../EtcdUI/Dockerfile
      args:
        ETCD_KEEPER_VERSION: ${ETCD_KEEPER_VERSION}
        EIS_VERSION: ${EIS_VERSION}
    image: ${DOCKER_REGISTRY}ia_etcd_ui:${EIS_VERSION}
    container_name: ia_etcd_ui
    hostname: ia_etcd_ui
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "EtcdUi"
      DEV_MODE: ${DEV_MODE}
    user: ${EIS_UID}
    secrets:
      - ca_etcd
      - etcd_root_cert
      - etcd_root_key
 
  modbus-tcp-master:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../modbus-master/
      dockerfile: $PWD/../modbus-master/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}modbus-master:${EIS_VERSION}
    container_name: modbus-tcp-master
    hostname: modbus-tcp-master
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "Modbus-TCP-Master"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      TCP_ENABLED : 1
      ZMQ_RECV_HWM: "1000"
      MY_APP_ID: 5
      MODBUS_MASTER_CONNECT_TIMEOUT: 30000
      MODBUS_MASTER_SESSION_TIMEOUT: 10
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      Clients: "MQTT-Export"
      WRITE_RESPONSE_TOPIC: "PL0_flowmeter1_write_response"
      SubTopics: "MQTT-Export/PL0_flowmeter1_write"
      PubTopics: "PL0_flowmeter1,PL0_flowmeter1_write_response"
      PL0_flowmeter1_cfg: "zmq_tcp,127.0.0.1:5656"
      PL0_flowmeter1_write_cfg: "zmq_tcp,127.0.0.1:5858"
      PL0_flowmeter1_write_response_cfg: "zmq_tcp,127.0.0.1:9999"
    #user: ${EIS_UID}
    secrets:
      - ca_etcd
      - etcd_Modbus-TCP-Master_cert
      - etcd_Modbus-TCP-Master_key

  mqtt_container:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../MQTT/
      dockerfile: $PWD/../MQTT/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
    image: ${DOCKER_REGISTRY}mqtt_container:${EIS_VERSION}
    container_name: mqtt_container
    hostname: mqtt_container
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "MQTT"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}

  mqtt-export:
    depends_on:
      - ia_eisbase
    build:
      context: $PWD/../mqtt-export/
      dockerfile: $PWD/../mqtt-export/Dockerfile
      args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: ${EIS_UID}
        EIS_USER_NAME: ${EIS_USER_NAME}
    image: ${DOCKER_REGISTRY}mqtt-export:${EIS_VERSION}
    container_name: mqtt-export
    hostname: mqtt-export
    network_mode: host
    restart: unless-stopped
    environment:
      AppName: "MQTT-Export"
      DEV_MODE: ${DEV_MODE}
      no_proxy: ${no_proxy}
      ZMQ_RECV_HWM: "1000" 
      MQTT_URL_FOR_EXPORT: "tcp://127.0.0.1:1883"
      CertType: "zmq"
      PROFILING_MODE: ${PROFILING_MODE}
      SubTopics: "Modbus-TCP-Master/PL0_flowmeter1"
      PL0_flowmeter1_cfg: "zmq_tcp,127.0.0.1:5656"
    #user: ${EIS_UID}
    secrets:
      - ca_etcd
      - etcd_MQTT-Export_cert
      - etcd_MQTT-Export_key
 
secrets:
  ca_etcd:
    file: provision/Certificates/ca/ca_certificate.pem
  etcd_root_cert:
    file: provision/Certificates/root/root_client_certificate.pem
  etcd_root_key:
    file: provision/Certificates/root/root_client_key.pem
  etcd_Modbus-TCP-Master_cert:
    file: provision/Certificates/Modbus-TCP-Master/Modbus-TCP-Master_client_certificate.pem
  etcd_Modbus-TCP-Master_key:
    file: provision/Certificates/Modbus-TCP-Master/Modbus-TCP-Master_client_key.pem
  etcd_MQTT-Export_cert:
    file: provision/Certificates/MQTT-Export/MQTT-Export_client_certificate.pem
  etcd_MQTT-Export_key:
    file: provision/Certificates/MQTT-Export/MQTT-Export_client_key.pem
