---
file:
  version: "1.0.0"
  author: "Intel"
  date: "Sun Sep 1 13:34:13 PDT 2019"
  description: "Data for Demo IOUnit data points"

datapoints:
- id: "DValve"
  attributes:
    type: "COIL"
    addr: 000001
    width: 1
  polling:
    pollinterval: 1000
    realtime: false
   
- id: "Point2"
  attributes:
    type: "COIL"
    addr: 000002
    width: 1
  polling:
    pollinterval: 1000
    realtime: false
