---
file:
    version: "1.0.0"
    author: "Intel"
    date: "Wed Sep 2 13:34:13 IST 2020"
    description: "scada config parameter file"

# URL's to be used for external broker
EXTERNAL_MQTT_URL: "tcp://127.0.0.1:1883"
qos_mqtt_comm: 1
