version: '3.6'
services:
  ia_etcd:
    build:
      context: ../
      dockerfile: ./dep/Dockerfile
      args:
       ETCD_VERSION: $ETCD_VERSION
       EIS_UID: $EIS_UID
    read_only: true
    image: ia_etcd:$EIS_VERSION
    restart: unless-stopped
    container_name: ia_etcd
    environment:
      HOST_IP: $HOST_IP
      ETCDCTL_API: 3
      DEV_MODE: $DEV_MODE
      ETCD_DATA_DIR: $ETCD_DATA_DIR
      ETCD_HOST: $ETCD_HOST
      ETCD_CLIENT_PORT: $ETCD_CLIENT_PORT
      ETCD_PEER_PORT: $ETCD_PEER_PORT
      ETCD_NAME: $ETCD_NAME
      ETCD_INITIAL_CLUSTER_STATE: $ETCD_INITIAL_CLUSTER_STATE
      ETCD_INITIAL_CLUSTER: $ETCD_INITIAL_CLUSTER
      no_proxy: $eis_no_proxy
      NO_PROXY: $eis_no_proxy
      http_proxy: $http_proxy
      https_proxy: $https_proxy
    volumes:
      - "vol_etcd:$ETCD_DATA_DIR"
    user: $EIS_UID
    # userns_mode: host
    security_opt:
      - no-new-privileges
    healthcheck:
      test:
      - CMD-SHELL
      - etcdctl endpoint health || exit 1
    ulimits:
      nofile:
        soft: "20000"
        hard: "40000"
    
  ia_etcd_provision:
    depends_on:
      - ia_etcd
    build:
       context: ../
       dockerfile: ./dep/Dockerfile.provision
       args:
        EIS_VERSION: ${EIS_VERSION}
        EIS_UID: $EIS_UID
    container_name: ia_etcd_provision
    read_only: true
    image: ia_etcd_provision:$EIS_VERSION
    volumes:
      - "../config:/EIS/etcd/config/:Z"
      - "../docker-compose.yml:/EIS/etcd/docker-compose.yml:Z"
    environment:
      ETCDCTL_API: 3
      ETCD_HOST: $ETCD_HOST
      ETCD_CLIENT_PORT: $ETCD_CLIENT_PORT
      DEV_MODE: ${DEV_MODE}
      no_proxy: $eis_no_proxy
      NO_PROXY: $eis_no_proxy
      http_proxy: $http_proxy
      https_proxy: $https_proxy
    user: $EIS_UID
    userns_mode: host
    security_opt:
      - no-new-privileges
    healthcheck:
      disable: true
    ulimits:
      nofile:
        soft: "20000"
        hard: "40000"
networks:
  default:
    external:
      name: uwc_nw

volumes:
  vol_etcd:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: ${EIS_INSTALL_PATH}/data/etcd/
   
