---
file:
  version: "1.0.0"
  author: "Intel"
  date: "Sun Sep 1 13:34:13 PDT 2019"
  description: "Data for well site 1"
id: "PL0"
description: "Well site 1"
devicelist:
- deviceinfo: "flowmeter_device.yml"
  id: "flowmeter"
  protocol:
    protocol: "PROTOCOL_TCP"
    ipaddress: "192.168.80.95"
    port: 502
    unitid: 1

- deviceinfo: iou_device.yml
  id: "iou"
  protocol:
    protocol: PROTOCOL_RTU
    slaveid: '10'
